### ISSUE TITLE
Weird intermittent issue with cache

### ISSUE THREAD

**Issue by kreisys** [codeship/jet-tutorial#8] opened 2016-03-03 19:00 UTC
This has been baffling me for several days now. Using a cached service, jet intermittently tries to pull the :latest tag instead of the :codeship-cache-{branch} tag. Since I don't push the :latest tag to the registry I end up with intermittent failures that seem very much random:

```
$ docker rmi myregistry.com/myapp:{latest,codeship-cache-master} ; jet steps --ci-branch=master
Error response from daemon: could not find image: no such id: myregistry.com/myapp:latest
Error response from daemon: could not find image: no such id: myregistry.com/myapp:codeship-cache-master
Error: failed to remove images: [myregistry.com/myapp:latest myregistry.com/myapp:codeship-cache-master]
{StepStarted=step_name:"Build myapp image"}
{PullImageStarted=image_name:"myregistry.com/myapp" service_name:"myapp_build"}
{StepFinished=step_name:"Build myapp image" type:STEP_FINISHED_TYPE_ERROR}
Error: image myapp:latest not found

$ docker rmi myregistry.com/myapp:{latest,codeship-cache-master} ; jet steps --ci-branch=master
Error response from daemon: could not find image: no such id: myregistry.com/myapp:latest
Error response from daemon: could not find image: no such id: myregistry.com/myapp:codeship-cache-master
Error: failed to remove images: [myregistry.com/myapp:latest myregistry.com/myapp:codeship-cache-master]
{StepStarted=step_name:"Build myapp image"}
{PullImageStarted=image_name:"myregistry.com/myapp" service_name:"myapp_build"}
{StepFinished=step_name:"Build myapp image" type:STEP_FINISHED_TYPE_ERROR}
Error: image myapp:latest not found

$ docker rmi myregistry.com/myapp:{latest,codeship-cache-master} ; jet steps --ci-branch=master
Error response from daemon: could not find image: no such id: myregistry.com/myapp:latest
Error response from daemon: could not find image: no such id: myregistry.com/myapp:codeship-cache-master
Error: failed to remove images: [myregistry.com/myapp:latest myregistry.com/myapp:codeship-cache-master]
{StepStarted=step_name:"Build myapp image"}
{PullImageStarted=image_name:"myregistry.com/myapp" service_name:"myapp_build"}
{StepFinished=step_name:"Build myapp image" type:STEP_FINISHED_TYPE_ERROR}
Error: image myapp:latest not found

$ docker rmi myregistry.com/myapp:{latest,codeship-cache-master} ; jet steps --ci-branch=master
Error response from daemon: could not find image: no such id: myregistry.com/myapp:latest
Error response from daemon: could not find image: no such id: myregistry.com/myapp:codeship-cache-master
Error: failed to remove images: [myregistry.com/myapp:latest myregistry.com/myapp:codeship-cache-master]
{StepStarted=step_name:"Build myapp image"}
{PullImageStarted=image_name:"myregistry.com/myapp" service_name:"myapp_build"}
{StepFinished=step_name:"Build myapp image" type:STEP_FINISHED_TYPE_ERROR}
Error: image myapp:latest not found

$ docker rmi myregistry.com/myapp:{latest,codeship-cache-master} ; jet steps --ci-branch=master
Error response from daemon: could not find image: no such id: myregistry.com/myapp:latest
Error response from daemon: could not find image: no such id: myregistry.com/myapp:codeship-cache-master
Error: failed to remove images: [myregistry.com/myapp:latest myregistry.com/myapp:codeship-cache-master]
{StepStarted=step_name:"Build myapp image"}
{PullImageStarted=image_name:"myregistry.com/myapp:codeship-cache-master" service_name:"myapp_build"}
{PullImageFinished=image_name:"myregistry.com/myapp:codeship-cache-master" service_name:"myapp_build"}
{BuildImageStarted=image_name:"myregistry.com/myapp" service_name:"myapp_build"}
{BuildImageStdout=image_name:"myregistry.com/myapp" service_name:"myapp_build"}: Step 1 : FROM node:4.2.3
{BuildImageStdout=image_name:"myregistry.com/myapp" service_name:"myapp_build"}:  ---> 14aadd36ad0c
{BuildImageStdout=image_name:"myregistry.com/myapp" service_name:"myapp_build"}: Step 2 : MAINTAINER Me
{BuildImageStdout=image_name:"myregistry.com/myapp" service_name:"myapp_build"}:  ---> Using cache
{BuildImageStdout=image_name:"myregistry.com/myapp" service_name:"myapp_build"}:  ---> 85162f600fc1
{BuildImageStdout=image_name:"myregistry.com/myapp" service_name:"myapp_build"}: Successfully built 85162f600fc1
{PushImageStarted=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: The push refers to a repository [myregistry.com/myapp] (len: 1)
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: Image already exists
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: Image already exists
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: Image already exists
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: Image already exists
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: Image already exists
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: Image already exists
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: Image already exists
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: codeship-cache-master: digest: sha256:bb461ab189138c02d674bb35b50220961c6c1acef3b229cb834cabc708092f76 size: 18846
{PushImageFinished=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}
{BuildImageFinished=image_name:"myregistry.com/myapp" service_name:"myapp_build"}
{StepFinished=step_name:"Build myapp image" type:STEP_FINISHED_TYPE_SUCCESS}

$ docker rmi myregistry.com/myapp:{latest,codeship-cache-master} ; jet steps --ci-branch=master
Untagged: myregistry.com/myapp:latest
Untagged: myregistry.com/myapp:codeship-cache-master
{StepStarted=step_name:"Build myapp image"}
{PullImageStarted=image_name:"myregistry.com/myapp" service_name:"myapp_build"}
{StepFinished=step_name:"Build myapp image" type:STEP_FINISHED_TYPE_ERROR}
Error: image myapp:latest not found

$ docker rmi myregistry.com/myapp:{latest,codeship-cache-master} ; jet steps --ci-branch=master
Error response from daemon: could not find image: no such id: myregistry.com/myapp:latest
Error response from daemon: could not find image: no such id: myregistry.com/myapp:codeship-cache-master
Error: failed to remove images: [myregistry.com/myapp:latest myregistry.com/myapp:codeship-cache-master]
{StepStarted=step_name:"Build myapp image"}
{PullImageStarted=image_name:"myregistry.com/myapp:codeship-cache-master" service_name:"myapp_build"}
{PullImageFinished=image_name:"myregistry.com/myapp:codeship-cache-master" service_name:"myapp_build"}
{BuildImageStarted=image_name:"myregistry.com/myapp" service_name:"myapp_build"}
{BuildImageStdout=image_name:"myregistry.com/myapp" service_name:"myapp_build"}: Step 1 : FROM node:4.2.3
{BuildImageStdout=image_name:"myregistry.com/myapp" service_name:"myapp_build"}:  ---> 14aadd36ad0c
{BuildImageStdout=image_name:"myregistry.com/myapp" service_name:"myapp_build"}: Step 2 : MAINTAINER Me
{BuildImageStdout=image_name:"myregistry.com/myapp" service_name:"myapp_build"}:  ---> Using cache
{BuildImageStdout=image_name:"myregistry.com/myapp" service_name:"myapp_build"}:  ---> 85162f600fc1
{BuildImageStdout=image_name:"myregistry.com/myapp" service_name:"myapp_build"}: Successfully built 85162f600fc1
{PushImageStarted=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: The push refers to a repository [myregistry.com/myapp] (len: 1)
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: Image already exists
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: Image already exists
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: Image already exists
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: Image already exists
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: Image already exists
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: Image already exists
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: Image already exists
{PushImageStdout=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}: codeship-cache-master: digest: sha256:bb461ab189138c02d674bb35b50220961c6c1acef3b229cb834cabc708092f76 size: 18846
{PushImageFinished=step_name:"Build myapp image" service_name:"myapp_build" image_name:"myregistry.com/myapp"}
{BuildImageFinished=image_name:"myregistry.com/myapp" service_name:"myapp_build"}
{StepFinished=step_name:"Build myapp image" type:STEP_FINISHED_TYPE_SUCCESS}
```
This is legit copy paste of this happening. I just search/replaced some identifying bits and added newlines between runs.

codeship-steps.yml:
```
- name: Build
  service: myapp_build
  command: /bin/true
  encrypted_dockercfg_path: dockercfg.encrypted
```

codeship-services.yml:
```
myapp_build:
  build:
    image: myregistry.com/myapp
    dockerfile_path: docker/build/myapp/Dockerfile
  cached: true
  encrypted_env_file: codeship.env.encrypted
```

Dockerfile:
```
FROM node:4.2.3
MAINTAINER Me
```
Jet version is 1.1.3

The weirdest thing is that it only happens in one project. If I take the files in here as pasted and start in a new directory, it will NEVER happen (put it in a loop for an hour). If I dumb down my project commenting everything until it's as pasted here, the strange behaviour continues. Any idea what would cause jet to alternate like this in a seemingly random fashion?

**Comment by bfosberry** [comment] 2016-03-03 23:37
Hey, thanks for reporting this. That is really weird! I'm looking for clues in the code our side. My first guess is its a parsing bug related to the image name, try adding a default port to "myregistry.com/myapp". Not only should it not be possible for it to pull "latest" during caching, it also should not fail if it can't pull the cache, only if it can't push.

This makes me wonder if this is actually related to caching. Does it still fail with caching turned off? I wonder if jet is reading your services file incorrectly. If it thinks no dockerfile is specified, it'll treat it like a pull instead of a build. 

1) is your dockerfile in ./docker/build/myapp/Dockerfile inside the build context
2) what was changed, if anything, for your last example to work?
3) Do you get the same results turning caching off (cached: false)

**Comment by kreisys** [comment] 2016-03-04 00:22
1) yes
2) nothing. I was just repeating the same command line over and over to show that it just has different result each time.
3) haven't thought of trying that before. but when trying now I'm getting similar behaviour. It would "alternate" between trying to fetch latest and just building the image. the former, as with caching enabled, results in an error.

**Comment by kreisys** [comment] 2016-03-09 18:33
Any update on this? I'm pretty sure it's unrelated to docker 1.10 caching issue (I've been using 1.9.1 all along)

**Comment by bfosberry** [comment] 2016-03-09 18:36
Yeah, agreed. We've been a little busy dealing with that the last week :P I'll take a look at this, see if I can refactor some code to add clarity or fix the issue.

**Comment by kreisys** [comment] 2016-03-09 18:37
No worries I assumed as much. Thank you!

**Comment by kreisys** [comment] 2016-03-10 21:03
I won't be able to send the entire context since it's proprietary software. Can you specify exactly which files you'd need?

**Comment by kreisys** [comment] 2016-03-10 22:13
I already tried the opposite without much success (starting from a clean tree that doesn't present this behaviour and incrementally adding my files). Tomorrow I'll try starting with the whole tree and gradually remove the source files to see if it has any effect... I'll keep you posted.

**Comment by kreisys** [comment] 2016-03-11 19:05
Ok so I managed to isolate this! So it has nothing to do with cache at all. These are my files:

codeship-services.yml:
```yaml
builder:
  build:
    image: dummy
    dockerfile_path: Dockerfile

tester:
  image: dummy
```

codeship-steps.yml:
```yaml
- name: Build image
  service: builder
  command: /bin/true
```

Dockerfile:
```dockerfile
FROM busy box
```

Now we run 'jet steps' repeatedly:
```
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{BuildImageStarted=image_name:"dummy" service_name:"builder"}
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Step 1 : FROM busybox
{BuildImageStdout=image_name:"dummy" service_name:"builder"}:  ---> 65e4158d9625
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Successfully built 65e4158d9625
{BuildImageFinished=image_name:"dummy" service_name:"builder"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{BuildImageStarted=image_name:"dummy" service_name:"builder"}
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Step 1 : FROM busybox
{BuildImageStdout=image_name:"dummy" service_name:"builder"}:  ---> 65e4158d9625
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Successfully built 65e4158d9625
{BuildImageFinished=image_name:"dummy" service_name:"builder"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{BuildImageStarted=image_name:"dummy" service_name:"builder"}
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Step 1 : FROM busybox
{BuildImageStdout=image_name:"dummy" service_name:"builder"}:  ---> 65e4158d9625
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Successfully built 65e4158d9625
{BuildImageFinished=image_name:"dummy" service_name:"builder"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{BuildImageStarted=image_name:"dummy" service_name:"builder"}
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Step 1 : FROM busybox
{BuildImageStdout=image_name:"dummy" service_name:"builder"}:  ---> 65e4158d9625
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Successfully built 65e4158d9625
{BuildImageFinished=image_name:"dummy" service_name:"builder"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ 
```
Notice the behaviour randomly alternating between building the image from the Dockerfile and using the currently available image. This seems to be caused by the mere existence of the second service "tester" that wants to use image built by the service "builder". Removing the "tester" service:
```yaml
builder:
  build:
    image: dummy
    dockerfile_path: Dockerfile
```
Results in consistent behaviour where it always builds:
```
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{BuildImageStarted=image_name:"dummy" service_name:"builder"}
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Step 1 : FROM busybox
{BuildImageStdout=image_name:"dummy" service_name:"builder"}:  ---> 65e4158d9625
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Successfully built 65e4158d9625
{BuildImageFinished=image_name:"dummy" service_name:"builder"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{BuildImageStarted=image_name:"dummy" service_name:"builder"}
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Step 1 : FROM busybox
{BuildImageStdout=image_name:"dummy" service_name:"builder"}:  ---> 65e4158d9625
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Successfully built 65e4158d9625
{BuildImageFinished=image_name:"dummy" service_name:"builder"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{BuildImageStarted=image_name:"dummy" service_name:"builder"}
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Step 1 : FROM busybox
{BuildImageStdout=image_name:"dummy" service_name:"builder"}:  ---> 65e4158d9625
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Successfully built 65e4158d9625
{BuildImageFinished=image_name:"dummy" service_name:"builder"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{BuildImageStarted=image_name:"dummy" service_name:"builder"}
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Step 1 : FROM busybox
{BuildImageStdout=image_name:"dummy" service_name:"builder"}:  ---> 65e4158d9625
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Successfully built 65e4158d9625
{BuildImageFinished=image_name:"dummy" service_name:"builder"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{BuildImageStarted=image_name:"dummy" service_name:"builder"}
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Step 1 : FROM busybox
{BuildImageStdout=image_name:"dummy" service_name:"builder"}:  ---> 65e4158d9625
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Successfully built 65e4158d9625
{BuildImageFinished=image_name:"dummy" service_name:"builder"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ jet steps
{StepStarted=step_name:"Build image"}
{BuildImageStarted=image_name:"dummy" service_name:"builder"}
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Step 1 : FROM busybox
{BuildImageStdout=image_name:"dummy" service_name:"builder"}:  ---> 65e4158d9625
{BuildImageStdout=image_name:"dummy" service_name:"builder"}: Successfully built 65e4158d9625
{BuildImageFinished=image_name:"dummy" service_name:"builder"}
{StepFinished=step_name:"Build image" type:STEP_FINISHED_TYPE_SUCCESS}
bash-3.2$ 
```

**Comment by kreisys** [comment] 2016-03-11 19:22
Also I managed to work around it by copying the "build" part from "builder" to "tester". Jet did the right thing and didn't build the image again. I'm sorry I didn't include the "tester" service in my original example. I stupidly assumed it's irrelevant as long as there's no step using it... -_-"

**Comment by bfosberry** [comment] 2016-03-17 16:58
Hey, this is a behavioural quirk of Jet, so what you are defining with those two entries is two sources for the image, one being built from Dockerfile and one being pulled from the repo:latest. Depending on the exact execution order of those two image creations, the image may come from a pull or build, which is why your issue was intermittent.

The correct way to handle this would be to define the dockerfile_path for your tester service also, which would enforce where the image should come from. It will still only be built once, but even if tester runs beforehand, the image source will be the same. 

I'll add a task our side to either a) enforce a unique source for image loading (i.e. pull for tester and separately build for app) although this may result in inconsistencies, or b) add an error or warning when build sections for the same image are not identical.

To clarify, instead of 

```
builder:
  build:
    image: dummy
    dockerfile_path: Dockerfile

tester:
  image: dummy
```

you want

```
builder:
  build:
    image: dummy
    dockerfile_path: Dockerfile

tester:
  build:
    image: dummy
    dockerfile_path: Dockerfile
```

Im going to close this issue, but feel free to open other issues or comment on this one.

**Closed by bfosberry** 2016-03-17 16:58 UTC

**Comment by kreisys** [comment] 2016-03-17 17:00
yep that's exactly what I ended up doing. thanks!

**Comment by treapp** [comment] 2016-07-28 17:33
I know this is a closed issue, but I ran into the same problem today with a build. In my testing, I have two services with different names - both refer to the same image name. However, in my steps, I only call one of the services. One would assume that a service that doesn't even get called from the steps file could refer to the same image name as another service. That seems not to be the case. 

Services file: 
`demo:
  build:
    image: registry.ironqloud.com:4567/tre/tre-api
    dockerfile_path: Dockerfile.demo

api_iq:
  build: 
    image: registry.ironqloud.com:4567/tre/tre-api
    dockerfile_path: Dockerfile.build `
Steps file (note that the 'demo' service is not being called):
`- name: Create build bundle for Docker images...
  service: trebuild
  command: "./build.sh"
- name: Pushing tre API image to Ironqloud for security testing...
  type: parallel
  steps:
    - name: Build and push API image to Ironqloud
      service: api_iq
      type: push
      tag: master
      image_name: registry.ironqloud.com:4567/tre/tre-api
      registry: registry.ironqloud.com:4567
      encrypted_dockercfg_path: ironqloudcfg.encrypted
    - name: Build and push Dashboard image to Ironqloud
      service: admin_iq
      type: push
      tag: master
      image_name: registry.ironqloud.com:4567/tre/tre-admin
      registry: registry.ironqloud.com:4567
      encrypted_dockercfg_path: ironqloudcfg.encrypted`

I solved this by commenting out the demo service in the services file, but this is not expected behavior. I would anticipate that services *not* being called by my steps file would have no bearing on my build whatsoever.

**Comment by rheinwein** [comment] 2016-07-29 08:35
Hi @treapp, just to clarify, are you experiencing problems with the cache, or just with the build runs? 

Right now, you can't use the same image name in multiple services simply because one would overwrite the other during the build process for the service. The services file is parsed and validated at the beginning of the build run and we assume if you include a service in the config file. Both services and steps are first-class citizens in the Jet world. Your build errors with an 'already been built' message to prevent overwriting the `registry.ironqloud.com:4567/tre/tre-api` image.

**Comment by WoLfulus** [comment] 2017-08-31 20:28
Strange enough the same image for multiple services were working perfectly fine for us until we added "args" to the build configuration.

And since codeship just support templating on image_tag, how am I supposed to create different build configurations (dev, staging, prod) ?

This was the only way we found to make it work, and now we can't anymore because of the build args (needs confirmation if it was really the case)

Doesn't really make sense.

**Comment by rheinwein** [comment] 2017-09-01 07:46
@WoLfulus Right now, templates are only supported in `image_tag`, but we know they'd be more useful in more places in the file, and have it in our feature request backlog. I don't have an ETA for that feature, but it's likely we'll tackle it along with other environment variable work.

If you're having an issue with build arguments, please open a ticket at helpdesk.codeship.com and we can help you out. Thanks!
